import type { Place } from "./domain";

export const samplePlaces: Place[] = [
  {
    id: "home-test-room",
    slug: "phong-thu-nghiem-tu-cong-vao",
    name: "Phòng thử nghiệm từ cổng vào",
    category: "rental",
    publicationStatus: "draft",
    city: "Hải Phòng",
    address: "Khu thử nghiệm cá nhân",
    summary:
      "Scene đầu tiên dùng để kiểm tra capture iPhone, train 3DGS, collision và luồng quay lại bản đồ.",
    routeHint: "Cổng -> lối vào -> phòng chính",
    privacyStatus: "private_draft",
    coordinates: [106.6881, 20.8449],
    scene: {
      id: "home-test-room-v1",
      title: "Cổng vào phòng thử nghiệm",
      status: "processing",
      format: "sog",
      hotspots: [
        {
          id: "hotspot-home-entry-info",
          kind: "info",
          title: "Điểm bắt đầu từ cổng",
          body: "Dừng ở cổng để so sánh ánh sáng, hướng đi và điểm mốc trước khi vào phòng.",
          position: { x: 0, y: 1.55, z: 0 },
          rotation: { yaw: 0 },
          payload: { label: "Cổng vào", importance: "entry" },
        },
        {
          id: "hotspot-home-audio-intro",
          kind: "audio",
          title: "Giới thiệu nhanh",
          body: "Audio guide ngắn để giải thích cách đi từ cổng vào điểm chính.",
          position: { x: 1.2, y: 1.45, z: -0.6 },
          rotation: { yaw: 25 },
          payload: { audioKey: "audio/home-test-room/intro-vi.mp3", durationSeconds: 35 },
        },
        {
          id: "hotspot-home-quiz-observe",
          kind: "quiz",
          title: "Kiểm tra quan sát",
          body: "Câu hỏi ngắn để xem người dùng có nhận ra mốc đường đi chính hay không.",
          position: { x: 2.1, y: 1.4, z: -1.4 },
          rotation: { yaw: 35 },
          payload: {
            question: "Điểm nào nên giữ ổn định khi quay lại scene?",
            options: ["Ánh sáng và mốc đường đi", "Zoom camera liên tục", "Đổi lens giữa chừng"],
            answerIndex: 0,
          },
        },
        {
          id: "hotspot-home-checkin",
          kind: "checkin",
          title: "Check-in đến điểm chính",
          body: "Điểm check-in mẫu cho luồng sinh viên xác nhận đã xem hết từ cổng vào phòng.",
          position: { x: 2.8, y: 1.35, z: -2.2 },
          rotation: { yaw: 45 },
          payload: { reward: "local-demo-checkin", userStatus: "checked_in" },
        },
      ],
    },
  },
  {
    id: "student-cafe-demo",
    slug: "quan-cafe-sinh-vien-mau",
    name: "Quán cafe sinh viên mẫu",
    category: "cafe",
    publicationStatus: "review",
    city: "Hải Phòng",
    address: "Gần khu trường học",
    summary: "Địa điểm mẫu cho hotspot, audio giới thiệu, check-in và quiz ngắn.",
    routeHint: "Mặt tiền -> quầy -> khu ngồi",
    privacyStatus: "permission_needed",
    coordinates: [106.6932, 20.8424],
    scene: {
      id: "student-cafe-demo-v1",
      title: "Mặt tiền và khu ngồi",
      status: "pending_capture",
      format: "sog",
    },
  },
  {
    id: "heritage-gate-demo",
    slug: "cong-di-tich-mau",
    name: "Cổng di tích mẫu",
    category: "heritage",
    publicationStatus: "published",
    city: "Hải Phòng",
    address: "Tuyến trải nghiệm di sản",
    summary:
      "Mẫu cho tuyến đi từ cổng vào trong, phù hợp kiểm tra cách chia scene khi ánh sáng thay đổi.",
    routeHint: "Cổng -> sân trước -> điểm dừng giới thiệu",
    privacyStatus: "publishable",
    coordinates: [106.6814, 20.8498],
    scene: {
      id: "heritage-gate-demo-v1",
      title: "Cổng và lối vào",
      status: "pending_capture",
      format: "sog",
    },
  },
];
